
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  reusable:
    uses: ryanhTesting/org-workflows/.github/workflows/reusable.yml@main
    with:
      variable1: "string var"
    secrets: inherit
    # secrets:
    #   secret1: ${{ secrets.secret1 }}
